version: '3.4'
services:
  back:
    image: inventory-manager-back
    build:
      dockerfile: ./Dockerfile
    links:
      - mongo
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

